version: '3.7'

services:
  nats:
    image: nats:2-alpine
    container_name: "nats-tracing_nats"
    ports:
      - "8222:8222"
      - "4222:4222"
    command:
      - "--http_port"
      - "8222"
      - "--port"
      - "4222"
      - "--debug"
      - "--js"
      - "--server_name"
      - "nats"
    networks:
      - nats-tracing
  nats-configure:
    container_name: "nats-tracing_configure"
    links:
      - nats
    build:
      dockerfile: ./tools/natscli/Dockerfile
    volumes:
      - ./tools:/tools:ro
    entrypoint: /tools/nats-migrations.sh
    environment:
      NATS_HOST: nats
      NATS_PORT: 4222
    networks:
      - nats-tracing
    depends_on:
        - nats
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: "nats-tracing_jaeger"
    ports:
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "5778:5778"
      - "6831:6831/udp"
      - "6832:6832/udp"
    restart: on-failure
    networks:
      - nats-tracing

networks:
  nats-tracing:
    name: pub
